In [1]:
import cupy as cp

In [4]:
k = cp.arange(10, dtype='f').reshape(2, 5)

In [5]:
k

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]], dtype=float32)

In [7]:
kernel = cp.ElementwiseKernel('float32 x, float32 y',
                              'float32 z',
                              """
                                  z = x + y;
                              """, 'simple_sum')

In [8]:
c = cp.arange(5, dtype='f')

In [9]:
c

array([0., 1., 2., 3., 4.], dtype=float32)

In [12]:
z =kernel(k, c)

In [13]:
import numpy as np

In [18]:
%time np.arange(200000000)

Wall time: 387 ms


array([        0,         1,         2, ..., 199999997, 199999998,
       199999999])

In [20]:
%time cp.arange(200000000)

OutOfMemoryError: Out of memory allocating 800,000,000 bytes (allocated so far: 800,003,584 bytes).